<?php

/**
 * @file
 * Provides field Entity Reference Widget Tree hooks for OG group audience tree.
 */

require_once DRUPAL_ROOT . '/' . drupal_get_path('module', 'og_group_audience_tree') . '/og_group_audience_tree.widget.inc';
require_once DRUPAL_ROOT . '/' . drupal_get_path('module', 'og_group_audience_tree') . '/og_group_audience_tree.field.inc';

/**
 * Implements hook_get_entity_hierarchy().
 */
function og_group_audience_tree_get_entity_hierarchy($element, $allowed_ids, $label = '') {
  if ($element['#field'] == 'og_group_audience_tree') {
    return _og_group_audience_tree_get_og_hierarchy($element['#allowed_bundles']['#parent_id'], $element['#allowed_bundles']['entity_type'], $element['#allowed_bundles']['bundle_names'], $allowed_ids, $element['#filter_view'], $label);
  }
}

/**
 * This function returns a hierarchy of OG groups in a nested array.
 *
 * @param int $parent_id
 *   The ID of the root of the OG hierarchy.
 * @param int $entity_type
 *   The entity type to restrict the child search.
 * @param string $bundle_names
 *   The bundle names to restrict the child search.
 *
 * @return array
 *   A nested array of the OG group's child objects.
 */
function _og_group_audience_tree_get_og_hierarchy($parent_id, $entity_type, $bundle_names, &$allowed, $filter, $label, $default = array()) {
  $entities = _og_group_audience_tree_get_children($parent_id, $entity_type, $bundle_names);
  $entity_info = entity_get_info($entity_type);

  $result = array();

  if ($filter != '') {
    foreach ($allowed as $k => $v) {
      if (array_key_exists($k, $entities)) {
        $entity =& $entities[$k];
        $children = _og_group_audience_tree_get_og_hierarchy($entity->{$entity_info['entity keys']['id']}, $entity_type, $bundle_names, $allowed, $filter, $label, $default);
        if (is_array($children)) {
          $entity->children = $children;
          $entity->children_selected = _og_group_audience_tree_children_selected($entity, $default, $entity_info['entity keys']['id']);
        }
        else {
          $entity->children_selected = FALSE;
        }
        $entity->TEST = $label;
        array_push($result, $entity);
      }
    }
  }
  elseif ($entities) {
    foreach ($entities as &$entity) {
      if ($filter == '' || array_key_exists($entity->{$entity_info['entity keys']['id']}, $allowed)) {
        $children = _og_group_audience_tree_get_og_hierarchy($entity->{$entity_info['entity keys']['id']}, $entity_type, $bundle_names, $allowed, $filter, $label, $default);
        if (is_array($children)) {
          $entity->children = $children;
          $entity->children_selected = _og_group_audience_tree_children_selected($entity, $default, $entity_info['entity keys']['id']);
        }
        else {
          $entity->children_selected = FALSE;
        }
        $entity->TEST = $label;
        array_push($result, $entity);
      }
    }
  }

  return $result;
}

/**
 * Function like taxonomy_get_children but doesn't load entire group audience.
 *
 * @param int $parent_id
 *   The ID of the OG group whose children you want to get.
 * @param int $entity_type
 *   The entity type.
 * @param string $bundle_names
 *   The bundle names.
 *
 * @return array
 *   Array of OG groups, each in the form array('id'=>$entity_id,'name'=>$name).
 */
function _og_group_audience_tree_get_children($parent_id, $entity_type, $bundle_names) {
  $etids = array();

  if ($parent_id) {
    // Get all children of the parent id in OG Membership table.
    $query = db_select('og_membership ', 'o');
    $query->fields('o', array('etid'));
    $query->join('field_data_group_group', 'g', 'g.entity_id= o.etid AND g.entity_type = o.entity_type');
    $query->condition('o.gid', $parent_id);
    $query->condition('o.entity_type', $entity_type);
    $results = $query->execute();

    // Create a table of entity ids.
    while ($entity = $results->fetchObject()) {
      if ($entity->etid != $parent_id) {
        $etids[$entity->etid] = $entity->etid;
      }
    }
  }
  else {
    $query1 = db_select('field_data_group_group', 'g')->fields('g', array('entity_id'));
    $query1->join('og_membership', 'o', 'o.etid= g.entity_id AND o.entity_type = g.entity_type');
    $query1->condition('g.entity_type', $entity_type);
    if ($bundle_names) {
      $bundles_allowed = db_or();
      foreach ($bundle_names as $bundle) {
        $bundles_allowed->condition('bundle', $bundle);
      }
      $query1->condition($bundles_allowed);
    }
    $query1->where('g1.entity_id = g.entity_id');
    $results = db_select('field_data_group_group', 'g1')
      ->fields('g1', array('entity_id', 'entity_type', 'bundle'))
      ->notExists($query1)->execute();

    // Create a table of entity ids.
    while ($entity = $results->fetchObject()) {
      $etids[$entity->entity_id] = ($entity->entity_id);
    }
  }

  return ($etids) ? entity_load($entity_type, $etids, $bundle_names ? array('type' => $bundle_names) : NULL) : NULL;
}

/**
 * Select children.
 */
function _og_group_audience_tree_children_selected($entities, $default, $id) {
  foreach ($entities->children as $entity) {
    if (isset($default[$entity->$id]) || $entity->children_selected) {
      return TRUE;
    }
  }
  return FALSE;
}

/**
 * Implements hook_get_entity_parent().
 */
function og_group_audience_tree_get_entity_parent($element, $parent_id) {
  if (!$parent_id) {
    return;
  }
  $query = db_select('og_membership ', 'o');
  $query->fields('o', array('gid'));
  $query->condition('o.etid', $parent_id);
  $query->condition('o.entity_type', $element['#display']['settings']['target_entity']);
  $results = $query->execute();

  // Create a table of entity ids.
  $etids = array();
  while ($entity = $results->fetchObject()) {
    if ($entity->gid != $parent_id) {
      $etids[] = $entity->gid;
    }
  }

  return $etids;
}
